### ISSUE TITLE
HIDPI问题

### ISSUE THREAD

**Issue by v21cesc** [sxqsfun/fcitx5-sogou-themes#3]
fedora 34 gnome桌面 4K分辨率开启了HIDPI x2放缩
虽然设置了按屏幕DPI显示，但每次进入桌面首次启动输入法时不是以HIDPI显示。
手动重启fcitx5可恢复正常，不知是皮肤问题还是fcitx5问题

**Comment by sxqsfun** [comment]
我也是外接4k的屏幕, 桌面是kde. 我觉得是 fcitx5 的问题. 目前我是手动设置 输入法字体大小来解决. (如果怀疑是皮肤的问题, 可用fcitx5默认皮肤测试一下便知)

**Comment by v21cesc** [comment]
> 我也是外接4k的屏幕, 桌面是kde. 我觉得是 fcitx5 的问题. 目前我是手动设置 输入法字体大小来解决. (如果怀疑是皮肤的问题, 可用fcitx5默认皮肤测试一下便知)

fcitx5本身问题
